import { CATEGORIES, VIDEO_TIERS } from './Categories';

export const sampleVideos = [
    {
    id: '1',
    vimeoId: '1120367976',
    title: 'Designer Premium Wedding Story Invite',
    description: 'Premium designer card for lovely milestone events.',
    duration: '0:53',
    pages: 8,
    price: 1499,
    originalPrice: 1799,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP04'
  },
  {
    id: '16',
    vimeoId: '1120465443',
    title: 'Royal Rajasthani Wedding Invite',
    description: 'Platinum-style wedding invite with premium luxury feel.',
    duration: '1:15',
    pages: 10,
    price: 1999,
    originalPrice: 2399,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP05'
  },
  {
    id: '2',
    vimeoId: '1118012894',
    title: 'Premium Hindu Wedding Invite',
    description: 'Exclusive luxury card made for your grand occasions.',
    duration: '1:09',
    pages: 8,
    price: 1199,
    originalPrice: 2499,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP01'
  },
  {
    id: '3',
    vimeoId: '1120367944',
    title: 'Premium Sikh Wedding Invite',
    description: 'Elite and luxury invite designed for top-class celebrations.',
    duration: '0:53',
    pages: 9,
    price: 1499,
    originalPrice: 1699,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP02'
  },
  {
    id: '4',
    vimeoId: '1120368126',
    title: 'Exclusive Hindu Wedding Invite/Radha Krishna theme',
    description: 'Exclusive luxury card made for grand occasions.',
    duration: '1:23',
    pages: 10,
    price: 1499,
    originalPrice: 1899,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP03'
  },
  {
    id: '4b',
    vimeoId: '1120367944',
    title: 'Premium Sikh Wedding Invite',
    description: 'Elite and luxury invite designed for top-class celebrations.',
    duration: '0:53',
    pages: 9,
    price: 1499,
    originalPrice: 1699,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP02'
  },
    {
    id: 'a4',
    vimeoId: '1121191856',
    title: 'Sleek Wedding ceremony Invite',
    description: 'Modern Wedding card design with minimalistic fonts.',
    duration: '0:23',
    pages: 4,
    price: 799,
    originalPrice: 999,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS, CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS05'
  },
  {
    id: '5',
    vimeoId: '1116372967',
    title: 'Elegant Mehandi Ceremony Invite',
    description: 'Sweet digital invite to make your mehandi memorable.',
    duration: '0:15',
    pages: 2,
    price: 249,
    originalPrice: 399,
    categories: [CATEGORIES.MEHNDI_CEREMONY],
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB01'
  },
    {
    id: '6',
    vimeoId: '1116372823',
    title: 'Simple Hindu Wedding Invitation',
    description: 'Beautiful and affordable wedding invitation design',
    duration: '0:27',
    pages: 4,
    price: 499,
    originalPrice: 699,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS],
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS02'
  },
  {
    id: '7',
    vimeoId: '1116373042',
    title: 'Royal Muslim Digital Invite',
    description: 'muslim themed card for grand wedding ceremony',
    duration: '0:31',
    pages: 6,
    price: 799,
    originalPrice: 999,
    categories: [CATEGORIES.MUSLIM_WEDDING_CARDS],
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG01'
  },
  {
    id: '8',
    vimeoId: '1116373062',
    title: 'Beautiful Roka Ceremony Invite',
    description: 'Beautiful engagement ceremony invitation design',
    duration: '0:23',
    pages: 4,
    price: 499,
    originalPrice: 699,
    categories: [CATEGORIES.ENGAGEMENT_CEREMONY],
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS04'
  },
  {
    id: '9',
    vimeoId: '1116373088',
    title: 'Fresh Sangeet Ceremony Invite',
    description: 'Simple, vibrant, and refreshing invite for sangeet ceremony',
    duration: '0:22',
    pages: 3,
    price: 299,
    originalPrice: 399,
    categories: [CATEGORIES.SANGEET_CEREMONY],
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB03'
  },
  {
    id: '10',
    vimeoId: '1118470496',
    title: 'Simple Christian Wedding Invite',
    description: 'Simple yet classy design to keep things elegant.',
    duration: '0:24',
    pages: 3,
    price: 299,
    originalPrice: 399,
    categories: [CATEGORIES.WEDDING],
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB02'
  },
  {
    id: '11',
    vimeoId: '1116372692',
    title: 'Classic Groom to be Invite',
    description: 'Minimal design to announce your special occasion with elegance.',
    duration: '0:21',
    pages: 3,
    price: 299,
    originalPrice: 399,
    categories: [CATEGORIES.GROOM_TO_BE],
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB04'
  },
  {
    id: '12',
    vimeoId: '1118477078',
    title: 'Classic Sangeet Celebration Invite',
    description: 'A timeless digital card, perfect for sangeet celebration.',
    duration: '0:30',
    pages: 3,
    price: 299,
    originalPrice: 399,
    categories: [CATEGORIES.SANGEET_CEREMONY],
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB06'
  },
  {
    id: '13',
    vimeoId: '1116372305',
    title: 'Modern Engagement ceremony invite',
    description: 'Trendy invite with updated look for engagement events',
    duration: '0:31',
    pages: 4,
    price: 499,
    originalPrice: 699,
    categories: [CATEGORIES.ENGAGEMENT_CEREMONY],
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS01'
  },
  {
    id: '14',
    vimeoId: '1116373000',
    title: 'Trendy Muslim Engagement Digital Invite',
    description: 'Modern engagement invite design with beautiful patterns.',
    duration: '0:28',
    pages: 4,
    price: 499,
    originalPrice: 599,
    categories: [CATEGORIES.MUSLIM_WEDDING_CARDS],
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS03'
  },
  {
    id: '15',
    vimeoId: '1116372878',
    title: 'Lovely Wedding Digital Invite',
    description: 'Sweet digital invite to make moments memorable.',
    duration: '0:20',
    pages: 3,
    price: 299,
    originalPrice: 399,
    categories: [CATEGORIES.HINDU_WEDDING_CARDS],
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB05'
  },
];
