import { CATEGORIES, VIDEO_TIERS } from './Categories';

export const sampleVideos = [
  {
    id: '1',
    vimeoId: '1116372305',
    title: 'Radha Krishna Wedding Invitation Video',
    description: 'Learn how to create your first digital wedding invitation',
    duration: '1:45',
    pages: 3,
    price: 1299,
    originalPrice: 2499,
    category: CATEGORIES.WEDDING,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP01'
  },
  {
    id: '2',
    vimeoId: '1116372692',
    title: 'Elegant Royal Wedding Invitation',
    description: 'Discover powerful tools to grow your business',
    duration: '1:20',
    pages: 3,
    price: 999,
    originalPrice: 1899,
    category: CATEGORIES.WEDDING,
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG02'
  },
  {
    id: '3',
    vimeoId: '1116372878',
    title: 'Classic Hindu Wedding Card',
    description: 'See how other businesses thrive with our platform',
    duration: '1:15',
    pages: 3,
    price: 799,
    originalPrice: 1499,
    category: CATEGORIES.HINDU_WEDDING_CARDS,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS03'
  },
  {
    id: '4',
    vimeoId: '1116372823',
    title: 'Simple Hindu Wedding Invitation',
    description: 'Beautiful and affordable wedding invitation design',
    duration: '0:30',
    pages: 2,
    price: 499,
    originalPrice: 899,
    category: CATEGORIES.HINDU_WEDDING_CARDS,
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB04'
  },
  {
    id: '5',
    vimeoId: '1116372967',
    title: 'Luxury Mehndi Ceremony Invite',
    description: 'Premium mehndi ceremony invitation with stunning visuals',
    duration: '1:45',
    pages: 4,
    price: 1199,
    originalPrice: 2299,
    category: CATEGORIES.MEHNDI_CEREMONY,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP05'
  },
  {
    id: '6',
    vimeoId: '1116373000',
    title: 'Golden Sangeet Invitation',
    description: 'Elegant sangeet ceremony invitation with music theme',
    duration: '1:50',
    pages: 3,
    price: 899,
    originalPrice: 1699,
    category: CATEGORIES.SANGEET_CEREMONY,
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG06'
  },
  {
    id: '7',
    vimeoId: '1116373042',
    title: 'Haldi Ceremony Invitation',
    description: 'Bright and colorful haldi ceremony invitation',
    duration: '1:20',
    pages: 2,
    price: 699,
    originalPrice: 1299,
    category: CATEGORIES.HALDI_CEREMONY,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS07'
  },
  {
    id: '8',
    vimeoId: '1116373062',
    title: 'Engagement Ceremony Invite',
    description: 'Beautiful engagement ceremony invitation design',
    duration: '2:00',
    pages: 3,
    price: 799,
    originalPrice: 1499,
    category: CATEGORIES.ENGAGEMENT_CEREMONY,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS08'
  },
  {
    id: '9',
    vimeoId: '1116373088',
    title: 'Save The Date Card',
    description: 'Elegant save the date announcement',
    duration: '0:30',
    pages: 1,
    price: 399,
    originalPrice: 799,
    category: CATEGORIES.SAVE_THE_DATE,
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB09'
  },
  {
    id: '10',
    vimeoId: '1107224531',
    title: 'Premium Anniversary Card',
    description: 'Luxurious anniversary celebration invitation',
    duration: '1:30',
    pages: 3,
    price: 1099,
    originalPrice: 2099,
    category: CATEGORIES.ANNIVERSARY_CARDS,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP10'
  },
  {
    id: '11',
    vimeoId: '1107234012',
    title: 'Modern Muslim Wedding Invitation',
    description: 'Contemporary Islamic wedding invitation with beautiful calligraphy',
    duration: '2:15',
    pages: 4,
    price: 1399,
    originalPrice: 2699,
    category: CATEGORIES.MUSLIM_WEDDING_CARDS,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP11'
  },
  {
    id: '12',
    vimeoId: '1107224531',
    title: 'Caricature Couple Wedding Invite',
    description: 'Fun and personalized caricature-style wedding invitation',
    duration: '1:35',
    pages: 3,
    price: 899,
    originalPrice: 1599,
    category: CATEGORIES.BUSINESS,
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG12'
  },
  {
    id: '13',
    vimeoId: '1107234012',
    title: 'Birthday Celebration Video Card',
    description: 'Vibrant and joyful birthday invitation with animations',
    duration: '1:10',
    pages: 2,
    price: 599,
    originalPrice: 1199,
    category: CATEGORIES.BIRTHDAY,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS13'
  },
  {
    id: '14',
    vimeoId: '1107224531',
    title: 'Simple Engagement Announcement',
    description: 'Minimalist engagement ceremony invitation design',
    duration: '0:45',
    pages: 2,
    price: 549,
    originalPrice: 999,
    category: CATEGORIES.ENGAGEMENT_CEREMONY,
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB14'
  },
  {
    id: '15',
    vimeoId: '1107234012',
    title: 'Traditional Haldi Ceremony Card',
    description: 'Bright yellow themed haldi ceremony invitation',
    duration: '1:25',
    pages: 3,
    price: 749,
    originalPrice: 1399,
    category: CATEGORIES.HALDI_CEREMONY,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS15'
  },
  {
    id: '16',
    vimeoId: '1107224531',
    title: 'Floral Mehndi Invitation',
    description: 'Beautiful floral patterns for mehndi ceremony',
    duration: '1:55',
    pages: 3,
    price: 999,
    originalPrice: 1899,
    category: CATEGORIES.MEHNDI_CEREMONY,
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG16'
  },
  {
    id: '17',
    vimeoId: '1107234012',
    title: 'Musical Sangeet Night Invite',
    description: 'Dance and music themed sangeet ceremony invitation',
    duration: '2:30',
    pages: 4,
    price: 1199,
    originalPrice: 2299,
    category: CATEGORIES.SANGEET_CEREMONY,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP17'
  },
  {
    id: '18',
    vimeoId: '1107224531',
    title: 'Vintage Save The Date',
    description: 'Classic vintage style save the date announcement',
    duration: '0:40',
    pages: 1,
    price: 449,
    originalPrice: 899,
    category: CATEGORIES.SAVE_THE_DATE,
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB18'
  },
  {
    id: '19',
    vimeoId: '1107234012',
    title: 'Golden Anniversary Celebration',
    description: 'Elegant golden anniversary invitation with memories',
    duration: '2:10',
    pages: 4,
    price: 1299,
    originalPrice: 2499,
    category: CATEGORIES.ANNIVERSARY_CARDS,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP19'
  },
  {
    id: '20',
    vimeoId: '1107224531',
    title: 'Royal Hindu Wedding Card',
    description: 'Majestic Hindu wedding invitation with traditional motifs',
    duration: '1:40',
    pages: 3,
    price: 899,
    originalPrice: 1699,
    category: CATEGORIES.HINDU_WEDDING_CARDS,
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG20'
  },
  {
    id: '21',
    vimeoId: '1107234012',
    title: 'Elegant Muslim Nikah Invitation',
    description: 'Beautiful Islamic nikah ceremony invitation',
    duration: '1:30',
    pages: 3,
    price: 799,
    originalPrice: 1499,
    category: CATEGORIES.MUSLIM_WEDDING_CARDS,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS21'
  },
  {
    id: '22',
    vimeoId: '1107224531',
    title: 'Fun Birthday Party Invite',
    description: 'Colorful and exciting birthday party invitation',
    duration: '1:05',
    pages: 2,
    price: 499,
    originalPrice: 999,
    category: CATEGORIES.BIRTHDAY,
    tier: VIDEO_TIERS.BASIC,
    code: 'VIDB22'
  },
  {
    id: '23',
    vimeoId: '1107234012',
    title: 'Cartoon Caricature Wedding',
    description: 'Playful cartoon-style caricature wedding invitation',
    duration: '1:50',
    pages: 3,
    price: 1099,
    originalPrice: 1999,
    category: CATEGORIES.BUSINESS,
    tier: VIDEO_TIERS.GOLD,
    code: 'VIDG23'
  },
  {
    id: '24',
    vimeoId: '1107224531',
    title: 'Romantic Engagement Story',
    description: 'Love story themed engagement ceremony invitation',
    duration: '2:20',
    pages: 4,
    price: 1199,
    originalPrice: 2199,
    category: CATEGORIES.ENGAGEMENT_CEREMONY,
    tier: VIDEO_TIERS.PREMIUM,
    code: 'VIDP24'
  },
  {
    id: '25',
    vimeoId: '1107234012',
    title: 'Minimalist Wedding Invite',
    description: 'Clean and modern minimalist wedding invitation',
    duration: '1:15',
    pages: 2,
    price: 699,
    originalPrice: 1299,
    category: CATEGORIES.WEDDING,
    tier: VIDEO_TIERS.SILVER,
    code: 'VIDS25'
  }
];
